baseurl = "http://hwangjjung.github.io/"
title = "mytitle"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Hwangjjung"
googleAnalytics = "XXX"
disqusShortname = "Hwangjjung"

[Author]
    name = "Hwangjjung"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "My headline"
    description = "My description"
    github = "https://github.com/hwangjjung"
[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
